const data = [
    {
        title: "cadillac",
        content: 
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veniam, dolor officiis quae, sed fugiat maxime tenetur, voluptatibus vel iure quisquam pariatur sequi veritatis. Esse recusandae tempora debitis eum praesentium aliquid placeat unde inventore. Cupiditate quos obcaecati nostrum tempore ab! Quasi autem pariatur perspiciatis, officiis soluta, obcaecati dignissimos, hic expedita odio optio suscipit molestiae similique tenetur temporibus odit. <br><br>Necessitatibus doloremque consequatur officia ea dolorem, et hic soluta, porro dolorum unde obcaecati expedita exercitationem minus quaerat cum, delectus voluptas praesentium aspernatur? Harum fuga, ab cum quia facere nesciunt perspiciatis. Alias hic voluptatibus ut pariatur deleniti dolores itaque. Mollitia perferendis corrupti inventore deserunt ad nulla corporis architecto officiis, quasi nesciunt, maiores tempora animi illo optio? Numquam sint qui maxime consequatur reiciendis facere ipsa, architecto error eligendi perferendis recusandae perspiciatis cupiditate et minima nemo omnis sit laboriosam quisquam distinctio soluta ea quia? Blanditiis ut ex alias laborum vel, eius sed doloremque error tempore ad illo quasi repellat earum ab ducimus consequatur! Sunt corrupti doloremque enim ipsum, earum officiis adipisci illum omnis veniam maiores deserunt exercitationem dolor tempora nam quaerat culpa, velit voluptate, error repellat iste praesentium?"
        ,
        image: "./pictures/cadillac-1.jpg",

    },
    {
        title: "ferrari",
        content:
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veniam, dolor officiis quae, sed fugiat maxime tenetur, voluptatibus vel iure quisquam pariatur sequi veritatis. Esse recusandae tempora debitis eum praesentium aliquid placeat unde inventore. Cupiditate quos obcaecati nostrum tempore ab! Quasi autem pariatur perspiciatis, officiis soluta, obcaecati dignissimos, hic expedita odio optio suscipit molestiae similique tenetur temporibus odit. Necessitatibus doloremque consequatur officia ea dolorem, et hic soluta, porro dolorum unde obcaecati expedita exercitationem minus quaerat cum, delectus voluptas praesentium aspernatur? Harum fuga, ab cum quia facere nesciunt perspiciatis. Alias hic voluptatibus ut pariatur deleniti dolores itaque. Mollitia perferendis corrupti inventore deserunt ad nulla corporis architecto officiis, quasi nesciunt, maiores tempora animi illo optio? Numquam sint qui maxime consequatur reiciendis facere ipsa, architecto error eligendi perferendis recusandae perspiciatis cupiditate et minima nemo omnis sit laboriosam quisquam distinctio soluta ea quia? Blanditiis ut ex alias laborum vel, eius sed doloremque error tempore ad illo quasi repellat earum ab ducimus consequatur! Sunt corrupti doloremque enim ipsum, earum officiis adipisci illum omnis veniam maiores deserunt exercitationem dolor tempora nam quaerat culpa, velit voluptate, error repellat iste praesentium?",
        image: "./pictures/ferrari-1.jpg",

    },
    {
        title: "peugeot",
        content: 
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veniam, dolor officiis quae, sed fugiat maxime tenetur, voluptatibus vel iure quisquam pariatur sequi veritatis. Esse recusandae tempora debitis eum praesentium aliquid placeat unde inventore. Cupiditate quos obcaecati nostrum tempore ab! Quasi autem pariatur perspiciatis, officiis soluta, obcaecati dignissimos, hic expedita odio optio suscipit molestiae similique tenetur temporibus odit. Necessitatibus doloremque consequatur officia ea dolorem, et hic soluta, porro dolorum unde obcaecati expedita exercitationem minus quaerat cum, delectus voluptas praesentium aspernatur? Harum fuga, ab cum quia facere nesciunt perspiciatis. Alias hic voluptatibus ut pariatur deleniti dolores itaque. Mollitia perferendis corrupti inventore deserunt ad nulla corporis architecto officiis, quasi nesciunt, maiores tempora animi illo optio? Numquam sint qui maxime consequatur reiciendis facere ipsa, architecto error eligendi perferendis recusandae perspiciatis cupiditate et minima nemo omnis sit laboriosam quisquam distinctio soluta ea quia? Blanditiis ut ex alias laborum vel, eius sed doloremque error tempore ad illo quasi repellat earum ab ducimus consequatur! Sunt corrupti doloremque enim ipsum, earum officiis adipisci illum omnis veniam maiores deserunt exercitationem dolor tempora nam quaerat culpa, velit voluptate, error repellat iste praesentium?",
        image: "./pictures/peugeot-1.jpg",

    },
    {
        title: "glickenhaus",
        content: 
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veniam, dolor officiis quae, sed fugiat maxime tenetur, voluptatibus vel iure quisquam pariatur sequi veritatis. Esse recusandae tempora debitis eum praesentium aliquid placeat unde inventore. Cupiditate quos obcaecati nostrum tempore ab! Quasi autem pariatur perspiciatis, officiis soluta, obcaecati dignissimos, hic expedita odio optio suscipit molestiae similique tenetur temporibus odit. Necessitatibus doloremque consequatur officia ea dolorem, et hic soluta, porro dolorum unde obcaecati expedita exercitationem minus quaerat cum, delectus voluptas praesentium aspernatur? Harum fuga, ab cum quia facere nesciunt perspiciatis. Alias hic voluptatibus ut pariatur deleniti dolores itaque. Mollitia perferendis corrupti inventore deserunt ad nulla corporis architecto officiis, quasi nesciunt, maiores tempora animi illo optio? Numquam sint qui maxime consequatur reiciendis facere ipsa, architecto error eligendi perferendis recusandae perspiciatis cupiditate et minima nemo omnis sit laboriosam quisquam distinctio soluta ea quia? Blanditiis ut ex alias laborum vel, eius sed doloremque error tempore ad illo quasi repellat earum ab ducimus consequatur! Sunt corrupti doloremque enim ipsum, earum officiis adipisci illum omnis veniam maiores deserunt exercitationem dolor tempora nam quaerat culpa, velit voluptate, error repellat iste praesentium?",
        image: "./pictures/glick-1.jpg",

    },
    {
        title: "porsche",
        content: 
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veniam, dolor officiis quae, sed fugiat maxime tenetur, voluptatibus vel iure quisquam pariatur sequi veritatis. Esse recusandae tempora debitis eum praesentium aliquid placeat unde inventore. Cupiditate quos obcaecati nostrum tempore ab! Quasi autem pariatur perspiciatis, officiis soluta, obcaecati dignissimos, hic expedita odio optio suscipit molestiae similique tenetur temporibus odit. Necessitatibus doloremque consequatur officia ea dolorem, et hic soluta, porro dolorum unde obcaecati expedita exercitationem minus quaerat cum, delectus voluptas praesentium aspernatur? Harum fuga, ab cum quia facere nesciunt perspiciatis. Alias hic voluptatibus ut pariatur deleniti dolores itaque. Mollitia perferendis corrupti inventore deserunt ad nulla corporis architecto officiis, quasi nesciunt, maiores tempora animi illo optio? Numquam sint qui maxime consequatur reiciendis facere ipsa, architecto error eligendi perferendis recusandae perspiciatis cupiditate et minima nemo omnis sit laboriosam quisquam distinctio soluta ea quia? Blanditiis ut ex alias laborum vel, eius sed doloremque error tempore ad illo quasi repellat earum ab ducimus consequatur! Sunt corrupti doloremque enim ipsum, earum officiis adipisci illum omnis veniam maiores deserunt exercitationem dolor tempora nam quaerat culpa, velit voluptate, error repellat iste praesentium?",
        image: "./pictures/porsche-1.jpeg",

    },
    {
        title: "toyota",
        content: 
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veniam, dolor officiis quae, sed fugiat maxime tenetur, voluptatibus vel iure quisquam pariatur sequi veritatis. Esse recusandae tempora debitis eum praesentium aliquid placeat unde inventore. Cupiditate quos obcaecati nostrum tempore ab! Quasi autem pariatur perspiciatis, officiis soluta, obcaecati dignissimos, hic expedita odio optio suscipit molestiae similique tenetur temporibus odit. Necessitatibus doloremque consequatur officia ea dolorem, et hic soluta, porro dolorum unde obcaecati expedita exercitationem minus quaerat cum, delectus voluptas praesentium aspernatur? Harum fuga, ab cum quia facere nesciunt perspiciatis. Alias hic voluptatibus ut pariatur deleniti dolores itaque. Mollitia perferendis corrupti inventore deserunt ad nulla corporis architecto officiis, quasi nesciunt, maiores tempora animi illo optio? Numquam sint qui maxime consequatur reiciendis facere ipsa, architecto error eligendi perferendis recusandae perspiciatis cupiditate et minima nemo omnis sit laboriosam quisquam distinctio soluta ea quia? Blanditiis ut ex alias laborum vel, eius sed doloremque error tempore ad illo quasi repellat earum ab ducimus consequatur! Sunt corrupti doloremque enim ipsum, earum officiis adipisci illum omnis veniam maiores deserunt exercitationem dolor tempora nam quaerat culpa, velit voluptate, error repellat iste praesentium?",
        image: "./pictures/toyota-1.jpg",

    },
    {
        title: "vanwall",
        content: 
        "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Veniam, dolor officiis quae, sed fugiat maxime tenetur, voluptatibus vel iure quisquam pariatur sequi veritatis. Esse recusandae tempora debitis eum praesentium aliquid placeat unde inventore. Cupiditate quos obcaecati nostrum tempore ab! Quasi autem pariatur perspiciatis, officiis soluta, obcaecati dignissimos, hic expedita odio optio suscipit molestiae similique tenetur temporibus odit. Necessitatibus doloremque consequatur officia ea dolorem, et hic soluta, porro dolorum unde obcaecati expedita exercitationem minus quaerat cum, delectus voluptas praesentium aspernatur? Harum fuga, ab cum quia facere nesciunt perspiciatis. Alias hic voluptatibus ut pariatur deleniti dolores itaque. Mollitia perferendis corrupti inventore deserunt ad nulla corporis architecto officiis, quasi nesciunt, maiores tempora animi illo optio? Numquam sint qui maxime consequatur reiciendis facere ipsa, architecto error eligendi perferendis recusandae perspiciatis cupiditate et minima nemo omnis sit laboriosam quisquam distinctio soluta ea quia? Blanditiis ut ex alias laborum vel, eius sed doloremque error tempore ad illo quasi repellat earum ab ducimus consequatur! Sunt corrupti doloremque enim ipsum, earum officiis adipisci illum omnis veniam maiores deserunt exercitationem dolor tempora nam quaerat culpa, velit voluptate, error repellat iste praesentium?",
        image: "./pictures/vanwall-1.jpg",

    },
];

export default data;